# Generated by Django 4.1.7 on 2023-04-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appuser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
